on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ghcr.io/mglolenstine/gtk4-cross:rust-gtk-4.8
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Clear package cache
        run: apt clean
      - name: Update package lists (again)
        run: apt update
      - name: Install dependencies
        run: apt-get install -y gtk4-devel
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
